plugin:
    default_locale: en
    locales: [en]
    allow_channels: true
    afk_invincibility: false
    # This is the default channel a player will be chatting in. A value of 'global'
    # means that they will chat to everyone on the server, while 'world' means
    # that only players on their current world will see their messages.
    default_channel: world
    global_channel_name: 'Global'
    # persist_user_settings will determine whether or not individual user settings
    # like localizations and channels will be persisted between sessions
    # if this is set to true, it will increase overhead by a small amount
    persist_user_settings: false
worlds:
    world:
        # if chat_allowed is true, users will be able to chat like normal on this world
        # if false, users will be effectively muted
        chat_allowed: true
        # if whisper_allowed is true, users will be able to send and receive whispers on this world
        # if false, they will be unable to send or receive whispers
        whisper_allowed: true
        # flood_limit is lines:second, so the default will limit players to 5 lines per 5 seconds
        # set this to 0:0 to disable flood limiting
        flood_limit: 5:5
        # flood_punish is type:duration, where type can be mute, kick, or ban
        # duration in seconds
        # set this to mute:0 to disable it
        flood_punish: mute:5
        # flood_punish: kick:0
        # flood_punish: ban:3000
groups:
    # ---
    # priority determines the priority of the group if multiple groups are detected
    # %p = prefix, %s = suffix
    # %c = channel, %w = world
    # %n = player name, %dn = player display name
    # %t = target, %dt = target display name (for whispers)
    # %afk = afk tag
    # %m = message text
    # ---
    default:
        priority: 1
        channel: ''
        prefix: '[default]'
        suffix: ''
        afk: ''
        format:
            global: '%p %n@%w: %m'
            message: '%p %n@%w: %m'
            whisper_send: ''
            whisper_receive: ''
    users:
        priority: 2
        channel: '&A[&B%c&A]'
        prefix: '&A[&B-&A]&B'
        suffix: ''
        afk: '&A[&7afk&A]'
        format:
            global: '%c %p %n&A@&B%w &A%afk&F: %m'
            message: '%c %p %n %afk&F: %m'
            whisper_send: '&6To &B%t&6>>&F %m'
            whisper_receive: '&6From &B%t&6>>&F %m'
    admins:
        priority: 3
        channel: '&A[%c]'
        prefix: '&A[&C@&A]&B'
        suffix: ''
        afk: '&A[&7afk&A]'
        format:
            global: '%c %p %n&A@&B%w &A%afk&F: %m'
            message: '%c%p%n%s%afk&F: %m'
            whisper_send: '&6To &B%t&6>>&F %m'
            whisper_receive: '&6From &B%t&6>>&F %m'