name: ChatSuite
main: net.krinsoft.chat.ChatCore
version: ${project.version}
author: krinsdeath
softdepend: [PermissionsBukkit, bPermissions, Multiverse-Core]

commands:
  cs:
    aliases: [csh, cshelp, csa, csafk, csw, cswhisper, csc, cschan, csj, csjoin, csl, csleave]
    description: The basic command for this plugin
    permission: chatsuite.commands.help
    usage: /<command>