name: ChatSuite
main: net.krinsoft.chat.ChatCore
version: maven-version-number
author: krinsdeath
softdepend: [PermissionsBukkit, bPermissions, Multiverse-Core, Privileges, Factions, Heroes]

commands:
  chatsuite:
    aliases:
      - c
      - cs
      - csh
      - csa
      - csafk
      - csw
      - csc
      - cscj
      - cscl
      - cscs
      - cscc
      - csci
      - csl
      - csd
      - csv
      - csn
      - nick
    description: The basic command for this plugin
    usage: /<command>
    