name: ChatSuite
main: net.krinsoft.chat.ChatCore
version: ${project.version}
author: krinsdeath
softdepend: [PermissionsBukkit, bPermissions, Multiverse-Core]

commands:
  chatsuite:
    aliases: [cs, csa, csafk, csw, cswhisper, csc, cschan, csj, csjoin, csl, csleave]
    description: The basic command for this plugin
    permission: chatsuite.commands.help
    usage: /<command>

permissions:
  chatsuite.commands.whisper:
    description: Allows this user to use '/whisper'
    default: false
  chatsuite.commands.afk:
    description: Allows this user to use '/afk'
    default: false
  chatsuite.commands.global:
    description: Allows this user to use '/global'
    default: false
  chatsuite.commands.join:
    description: Allows this user to use '/join'
    default: false
  chatsuite.commands.leave:
    description: Allows this user to use '/leave'
    default: false
  chatsuite.commands.*:
    description: Enables all chat commands
    default: op
    children:
      chatsuite.commands.whisper: true
      chatsuite.commands.afk: true
      chatsuite.commands.global: true
      chatsuite.commands.join: true
      chatsuite.commands.leave: true
