name: ChatSuite
main: net.krinsoft.chat.ChatCore
version: maven-version-number
author: krinsdeath
softdepend: [PermissionsBukkit, bPermissions, Multiverse-Core, Privileges, Factions, Heroes]
website: http://dev.bukkit.org/server-mods/chatsuite/

commands:
  chatsuite:
    aliases: [chat]
    description: ChatSuite's base (and fallback) command.
    usage: |
      /<command> channel ...
      /<command> group ...
      /<command> user ...
  cgroup:
    aliases: [cg]
    description: ChatSuite's base group command.
    usage: /<command> [group] [option] [value]
  cuser:
    aliases: [cu]
    description: ChatSuite's base user command.
    usage: /<command> [user] [option] [value]
  channel:
    aliases: [ch]
    description: ChatSuite's root channel command, for basic and advanced channel administration.
    usage: |
      /<command> ?                          - Show this message.
      /<command> msg [channel] [message]    - Send a message to the specified channel.
      /<command> join [channel]             - Join the specified channel.
      /<command> part [channel]             - Leave the specified channel.
      /<command> invite [channel] [player]  - Invite the specified user to the channel.
      /<command> create [channel]           - Create the specified channel.
      /<command> set [channel] [option] ... - Sets the specified option for the given channel.
  msg: # done
    aliases: [chm, m]
    description: Sends a message to the specified channel.
    usage: /<command> [channel] [message]
  join: # done
    aliases: [chj, j]
    description: Joins the specified channel.
    usage: /<command> [channel]
  part: # done
    aliases: [chp, p]
    description: Leaves the specified channel.
    usage: /<command> [channel]
  boot: # done
    aliases: [chb, b]
    description: Kicks the specified player from the given channel.
    usage: /<command> [channel] [player]
  create: # done
    aliases: [chc, c]
    description: Creates the specified channel, as long as it doesn't already exist.
    usage: /<command> [channel]
  invite: # done
    aliases: [chi, inv]
    description: Invites a player to the channel.
    usage: /<command> [channel] [player]
  admin:
    aliases: [adm, cha]
    description: Adds a user as an admin for a channel.
    usage: |
      /<command> [channel] add [player]
      /<command> [channel] remove [player]
  whisper: # done
    aliases: [w]
    description: Sends a message to the specified player.
    usage: |
      /<command> [player] [message]         - Send a message to the specified player.
  reply:
    aliases: [r]
    description: Replies to the last person to send you a message.
    usage: |
      /<command> [message]                  - Reply to the last person who /whisper'd you.
  target:
    aliases: [t]
    description: Sets your current chat target.
    usage: |
      /<command> c:[channel]                - Allows you to chat directly to a channel.
      /<command> p:[player]                 - Allows you to chat directly to a player.
  mute:
    description: Mutes the specified player.
    usage: |
      /<command> c:channel
      /<command> p:player
  nickname:
    aliases: [nick]
    description: Changes your display name.
    usage: |
      /<command> [nickname]                 - Change your nickname.
      /<command> [player] [nickname]        - Change the specified player's nickname.
      /<command> -r [player]                - Reset the specified player's nickname.
      /<command> -l                         - List all current players with nicknames.
      /<command>                            - Reset your own nickname.
  afk:
    description: Toggles your afk status, with an optional message.
    usage: |
      /<command> [message]      - Sets you to afk with the given message.
      /<command>                - Toggles your afk status.
  irc:
    description: Allows changing various settings for the IRC Bot.
    usage: |
      /<command> connect        - Connects the IRC bot
      /<command> quit           - Shuts the IRC bot off
      /<command> nick [nick]    - Changes the bot's nickname
      /<command> set [option].. - Changes various settings of the IRC bot

permissions:
  chatsuite.bypass.*:
    description: Allows bypassing admin and owner rights on channels.
    children:
      chatsuite.bypass.admin: true
      chatsuite.bypass.invite: true
      chatsuite.bypass.join: true
      chatsuite.bypass.boot: true
      chatsuite.bypass.set: true
  chatsuite.commands:
    description: All of ChatSuite's basic user commands.
    children:
      chatsuite.nick: true
      chatsuite.nick.other: true
      chatsuite.whisper: true
      chatsuite.afk: true
      chatsuite.target: true
      chatsuite.reply: true
  chatsuite.commands.admin:
    description: All of ChatSuite's administrative commands.
    children:
      chatsuite.reload: true
      chatsuite.version: true
      chatsuite.debug: true
  chatsuite.channel.list.all:
    description: Allows a user to list all active channels.
  chatsuite.nick.other:
    description: Allows a user to change another user's nickname.