name: ChatSuite
main: net.krinsoft.chat.ChatCore
version: ${project.version}-${project.build.number}
author: krinsdeath
softdepend: [PermissionsBukkit, bPermissions, Multiverse-Core, Privileges]

commands:
  cs:
    aliases:
      - csh
      - cshelp
      - csa
      - csafk
      - csw
      - cswhisper
      - csc
      - cschan
      - cschannel
      - cscj
      - cscjoin
      - cscl
      - cscleave
      - cscs
      - cscsay
      - cscc
      - csccreate
      - csci
      - cscinvite
      - csl
      - cslist
      - csd
      - csv
    description: The basic command for this plugin
    usage: /<command>